# Generated by Django 2.2.24 on 2021-11-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizie', '0004_auto_20211113_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='desc',
        ),
    ]
