# Generated by Django 2.2.24 on 2021-11-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizie', '0005_remove_question_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selopt', models.CharField(max_length=100)),
                ('correct', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizie.Question')),
            ],
        ),
    ]
